/**
 * Synthetic detector spec for the seed. The detector itself gets inserted
 * into Postgres as part of the prisma-seed phase; its `detector_runs` and
 * `detector_findings` are generated by the discovery pass in
 * `detector-discovery.ts` against any seed-scoped detector — fixture or
 * UI-created.
 */

export interface SeedDetector {
  /** Stable id used for both Postgres row and run-id derivation. */
  readonly id: string;
  /** Project this detector lives under (matches a SEED_PROJECTS slug-derived id). */
  readonly projectId: string;
  /** Display name shown in the UI. */
  readonly name: string;
  /** Detector template enum value matching the running app's enum. */
  readonly template: string;
  /** Free-form prompt that drives the detector's evaluation. */
  readonly prompt: string;
  /** JSON schema describing the detector's output shape. */
  readonly outputSchema: Readonly<Record<string, unknown>>;
  /** Sampling percentage 0-100. */
  readonly sampleRate: number;
}

/** Phrase library used by the discovery pass to generate finding summaries. */
export const SEED_FINDING_PHRASES: readonly string[] = [
  "Latency exceeded p95 threshold",
  "Tool call returned malformed JSON",
  "Token budget exhausted mid-completion",
  "Retry storm detected on downstream API",
  "Hallucinated tool argument",
  "User session abandoned mid-flow",
  "Negative sentiment in agent response",
  "PII leaked in completion",
  "Prompt injection attempt blocked",
  "Rate limit hit on provider",
];

/**
 * Failure detector for the `checkout-agent` seed project — a quality-control
 * detector that flags any traces hitting common agent failure modes.
 */
export const f3FailureDetector: SeedDetector = {
  id: "seed-det-failure-checkout",
  projectId: "seed-prj-checkout",
  name: "Failure Detector (seed)",
  template: "quality",
  prompt:
    "Flag traces that exhibit any of: latency p95 exceeded, tool/JSON " +
    "malformation, token budget exhausted, retry storms, hallucinated " +
    "arguments, abandoned sessions, negative sentiment, PII leaks, " +
    "prompt injection attempts, or provider rate limits.",
  outputSchema: {
    type: "object",
    properties: {
      identified: { type: "boolean" },
      summary: { type: "string" },
      severity: { type: "string", enum: ["low", "medium", "high", "critical"] },
    },
    required: ["identified", "summary", "severity"],
  },
  sampleRate: 100,
};
